version: '3.8'
services:
  hapibeebackend-app:
    image: hapibeebackend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vsgate-s1.dei.isep.ipp.pt:11171/HapiBee3
      - SPRING_DATASOURCE_USERNAME=HapiBee
      - SPRING_DATASOURCE_PASSWORD=admin
      - PORTAL-ENDPOINT=http://mock-portal-app:8081/
      - SPRING_MAIL_HOST=smtp.office365.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=beesenderbzzz@hotmail.com
      - SPRING_MAIL_PASSWORD=isep.engreq.10
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    ports:
      - 8080:8080

  mock-portal-app:
    image: mock-portal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - DESTINATION_APPLICATION_URL=http://hapibeebackend-app:8080/
    ports:
      - 8081:8081

