# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  mock-portal-app:
    image: mock-portal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - DESTINATION_APPLICATION_URL=http://localhost:8080/

    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: Dockerfile